language: bash
services: docker

env:
  - DOCKER_DIR=8/jre-alpine DOCKER_TAG=8-jre-alpine
  - DOCKER_DIR=10/jre DOCKER_TAG=10-jre
  - DOCKER_DIR=11/jre DOCKER_TAG=11-jre

script:
  - cd spring-boot-web/$DOCKER_DIR
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t zxdkhb/spring-boot-web:$DOCKER_TAG .
      docker build -t zxdkhb/spring-boot-web:mce-cn-$DOCKER_TAG --build-arg uid=1001 --build-arg gid=1001 --build-arg TZ=Asia/Shanghai .
      docker build -t zxdkhb/spring-boot-web:mce-com-$DOCKER_TAG --build-arg uid=1001 --build-arg gid=1001 --build-arg TZ=America/New_York .
    )
  - cd -

after_script:
  - docker images

deploy:
  on:
    branch: master
  provider: script
  script: bash publish.sh zxdkhb/spring-boot-web $DOCKER_TAG

# vim: set et ts=2 sw=2:
